name: simplist_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_reorderable_list: ^1.0.8
  animations: ^2.0.11
  auto_route: ^9.1.0
  clock: ^1.1.1
  flex_seed_scheme: ^3.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.1
  implicitly_animated_reorderable_list_2: ^0.6.0
  pocketbase: ^0.18.1
  pocketbased: ^0.1.0
  riverpod: ^2.5.1
  rivership: ^0.1.2
  rxdart: ^0.28.0
  sliver_tools: ^0.2.12

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lintervention: ^0.1.1
  rivership_test: ^0.1.0+2

flutter:
  uses-material-design: true
